name: inventory_app
description: A Flutter Inventory Management App
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.5

  # Networking
  http: ^1.6.0
  dio: ^5.2.1

  # Env variables
  flutter_dotenv: ^6.0.0

  # UI / Utils
  fluttertoast: ^9.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.5

  # Local storage
  shared_preferences: ^2.5.3

  # Images
  image_picker: ^0.8.7+4
  cached_network_image: ^3.2.3
  mime: ^1.0.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/placeholder.png
